### PR TITLE
make nlohmann-json submodule

### PR DESCRIPTION
**Pull request by KnightMurloc**
why not make nlohmann json a submodule just like ixwebsocket?

### CODE REVIEW

**Comment by ouwou** [comment]
is this really necessary though? the submodule is like 200mb which is pretty unreasonable. i think its better to just make people figure out how to install nlohmann/json which isnt that hard since its just some headers

**Comment by KnightMurloc** [comment]
this is the point. if it's just header files then why install it in the system? especially if it is needed only for build. And the fewer dependencies, the better.

**Comment by ouwou** [comment]
well its a 200mb repo which is really excessive. its very easy to install it to the proper location anyways. making the default (not having it installed) result in a 200mb download for what should be ~100kb seems pretty bad. isnt it reasonable to expect that nlohmann/json is already somewhere on the system already?

**Comment by KnightMurloc** [comment]
> isnt it reasonable to expect that nlohmann/json is already somewhere on the system already?

Maybe. but the proposed edits are first checked for installation in the system and only then the submodule is used. if you don't want to add it as a git submodule then we can only do it at the cmake level so that those who don't want to install can clone manually. by the way, if you clone only the last commit, then the size will be 21 MB.

**Comment by ouwou** [comment]
maybe FetchContent could work here? the release archives are 100kb. in either case i think the proper way to include it in cmake would be `target_link_libraries(abaddon nlohmann_json::nlohmann_json)` (if find_package succeeds though it would still use the INCLUDE_DIRS/LIBRARIES thing). im still curious though, is not having nlohmann/json installed a problem you ran into here? im just wondering what motivated the change

**Comment by KnightMurloc** [comment]
> im just wondering what motivated the change

it's simply more convenient. when such small libraries do not need to be installed into the system.

**Pull request closed without merging**
