### PR TITLE
CMake: Refactoring

### PR DESCRIPTION
**Pull request by NexAdn**
This PR refactors parts of the CMake system to adjust it to more modern CMake practices and to replace some of our own module code with distribution-supplied code.

* Find modules for packages that have their own distribution CMake modules are removed
* The variable-based approach for linking against libraries is replaced with the modern target-based approach, removing the need to set `target_include_directories()`.

This also implicitly solves the problem with finding simpleini discussed in #48, since now the include paths are correctly set.

### CODE REVIEW

**Comment by NexAdn** [comment]
By the way: Most of the find modules use pkg-config anyway and almost all of these packages ship with pkg-config files. If we add the dependency on pkg-config (which is used for many software builds already), we could also get rid of most–if not all–find modules.

**Comment by DyXel** [comment]
> If we add the dependency on pkg-config (which is used for many software builds already), we could also get rid of most–if not all–find modules.

Now switching to Meson doesn't seem so horrible 👀 

I think the find modules are mostly to be used when building on Windows.

**Comment by ouwou** [comment]
yeah id rather not require pkg-config. it just makes it easier in a lot of cases for mac and linux but doesnt really do anything on windows.

**Comment by ouwou** [comment]
ill be rewriting most of this myself soon

**Comment by eli-schwartz** [comment]
> Now switching to Meson doesn't seem so horrible eyes

> I think the find modules are mostly to be used when building on Windows.


If you were going to switch to Meson, the gtk stack uses Meson already so you would be able to build gtkmm and its dependencies as a Meson subproject on Windows.

**Pull request closed without merging**
