### PR TITLE
add support for animated reactions and images 

### PR DESCRIPTION
**Pull request by TheMorc**
https://github.com/uowuo/abaddon/assets/13377926/c3b61b93-1e17-4be8-8370-36a2db635b98

https://github.com/uowuo/abaddon/assets/13377926/67860e12-db2b-42c4-9d2f-89d55594b41a

https://github.com/uowuo/abaddon/assets/13377926/90fb826b-f541-4dc2-b0ee-c00ff57b7e23

EDIT: One thing that is probably missing is checking for ShowAnimations in LazyImage

### CODE REVIEW

**Comment by ouwou** [comment]
yeah we do want to check ShowAnimations but id rather it not be done in LazyImage itself. also the main reason images arent animated already is cuz GTK's gif rendering is really really memory and cpu intensive, so i think there should probably be another option so you can have animations excluding attachments

**Comment by TheMorc** [comment]
> yeah we do want to check ShowAnimations but id rather it not be done in LazyImage itself. 

>i think there should probably be another option so you can have animations excluding attachments

I'll probably add an option into the list called something like ShowAttachmentAnimations or ShowAnimatedGIFs (or something more appropriate)
and that options property could be used later in the ImageComponent for gifs instead of being in the LazyImage itself.
But I'm not sure what about those reactions tho


I'll probably figure something out and get back later with commits in the repo 🙃

**Comment by ouwou** [comment]
sounds good. i think reactions are fine to bunch under ShowAnimations along with everything else since theyre very small

**Comment by ouwou** [comment]
anything else you think needs to be done or is it good to go? ill give it a test myself tomorrow probably

**Comment by TheMorc** [comment]
it should be good to go as is imo

**Comment by ouwou** [comment]
reactions dont seem to work. `reaction.Emoji.IsAnimated` is an [optional](https://github.com/uowuo/abaddon/blob/c86f1e16381fe699bd4adb6b6c8f3aba6124788e/src/discord/emoji.hpp#L15) so right now youre technically checking if the optional exists (it can be false and this would evaluate to true) so the proper check would be `reaction.Emoji.IsAnimated.has_value() && *reaction.Emoji.IsAnimated`. im kinda confused as to how it worked at all in the video you attached 😹. the image embed stuff looks fine though. maybe we can split the reaction stuff out into another PR so we can merge the image stuff since reactions might require some trickery to get working. also if you could clang-format it thatd be nice too

**Review by tawnylure — APPROVED** [review]
looks good.

**Comment by ouwou** [comment]
closing for now since ive gone ahead and done animated reactions. i also think itd be really nice if we could use something like libnsgif for drawing the big image embeds but that might be a pain in the ass, so ig im still open to doing what you have for image embeds as a stopgap if u want to update this

**Pull request closed without merging**
