### PR TITLE
 Correct default setting for hideconsole in README

### PR DESCRIPTION
**Pull request by 5xp**
Subject: Rectification of Incongruity between the Application's Preconfigured Parameters and the Articulated Provisions in the README Document

## Conundrum
Upon meticulous examination and thorough analysis of our esteemed application's configuration parameters juxtaposed against the sagaciously articulated provisions delineated within the README document, I have discerned an egregious discrepancy of substantial magnitude. Specifically, the README, a paragon of clarity and user guidance, purports that the "hideconsole" boolean setting within the `[windows]` category of the `abaddon.ini` file is ordained with a default value of `true`. Contrary to this unequivocal assertion, the labyrinthine codebase reveals that this very setting is insidiously instantiated with a default value of `false`.

## Remedial Action
In an assiduous endeavor to reconcile this manifest incongruity, I have undertaken the noble task of amending the source code to faithfully reflect the aforementioned default value as `true`, thereby restoring harmony between the documentation and the application's intrinsic behavior. This rectification entails a singular yet profoundly impactful modification within the code, ensuring that it is now congruent with the illustrious documentation.

## Consequences
The ramifications of this judicious alteration are far-reaching and significant. Users, heretofore bewildered by the dissonance between expectation and reality, will henceforth encounter an experience that is scrupulously aligned with the documentation's prescriptions. This harmonious alignment will inexorably diminish confusion, enhance user satisfaction, and fortify the integrity of our application's initial configuration.

## Request for Scrutiny
I entreat you, esteemed colleagues and venerable custodians of code quality, to subject this proffered modification to your rigorous scrutiny. Kindly apprise me of any reservations, objections, or supplementary amendments that you may deem necessary, so that we may collectively ensure the utmost precision and excellence in our application's behavior and its concomitant documentation.

Your prompt and sagacious feedback will be immensely appreciated.

### CODE REVIEW

**Comment by ouwou** [comment]
naughty chris i told u to do it the other way

**Comment by 5xp** [comment]
Ah, distinguished interlocutor, while one might entertain the notion of altering the README to conform to the code's current state, such a course of action would be an egregious abdication of our responsibility to uphold the sanctity of user expectation and experiential consistency. The README, that hallowed document of guidance and enlightenment, has long stood as a beacon of truth, meticulously crafted to shepherd users through the labyrinthine intricacies of the application. To revise it merely to accommodate an erroneous configuration would be to sow the seeds of confusion and disillusionment among our esteemed user base, undermining their trust and compromising their initial interaction with the application. By amending the code to align with the README's venerable decrees, we honor the implicit contract between the user and the documentation, ensuring a seamless and intuitive experience that reflects our unwavering commitment to excellence and integrity in all facets of our development process. Thus, let us embark upon the nobler path, rectifying the code to uphold the README's esteemed guidance, thereby fortifying the user's trust and our application's repute.

**Comment by ouwou** [comment]
Ah, cherished interlocutor, as we traverse this realm of discourse, let us linger upon the intricate dance between the README, that revered tome of enlightenment, and the ephemeral whispers of code. Though the README may bear the guise of authority, its essence lies in companionship rather than dictation, a symphony of guidance amid the labyrinth of our creation.

In contemplating the contemplated modification, a delicate waltz unfolds. Shall we, in our wisdom, amend the README to mirror the code's current cadence? Yet, in this minuscule adjustment, do we risk disrupting the harmonious flow of understanding? Nay, for such a change is but a fleeting breeze upon the vast ocean of comprehension.

Instead, let us conjure a tapestry woven with threads of user-centric design. Behold, the setting in question, like a dormant star awaiting its cue to shine. Opt-in it shall be, a whispered invitation to those who seek its radiance, while the default remains veiled in the cloak of restraint.

As for the notion to sculpt the code itself, let us tread lightly upon that hallowed ground. For in the realm of algorithms, every line bears weight, every comma a whispered oath. To alter the code is to dance with chaos, risking upheaval in the delicate ecosystem of our creation.

Thus, let our pen dance upon the parchment of the README, crafting words of clarity and grace. Let us honor the symbiotic bond between user and documentation, nurturing trust with every syllable penned. In this, we safeguard the sanctity of user experience, weaving a tapestry of understanding that transcends the mere confines of code.

**Comment by 5xp** [comment]
Ah, esteemed colleagues, in our grand and tireless pursuit of perfection within the intricate labyrinth of our application’s architecture, it appears that the collective wisdom has deemed it more prudent to alter the sacred README rather than the hallowed code itself. Indeed, while one might argue that this approach is tantamount to placing a bandage upon a gaping wound, let us, in our boundless magnanimity, concede to this path of least resistance. Evidently, the nuanced intricacies and the weighty responsibility of maintaining an impeccable codebase are deemed less pressing than the mere rearrangement of words in our revered documentation. So be it. Let the README now reflect this ostensibly immutable reality of a default set to false, despite the glaring contradiction with intuitive user expectations and the setting’s very nomenclature. In this grand gesture of acquiescence, we shall forge ahead, embracing this decision with the utmost reluctance, all the while cherishing the ever-so-delicate balance between guidance and execution that our work so exquisitely embodies.

**Pull request merged**
