### PR TITLE
Greatly inprove rendering times

### PR DESCRIPTION
**Pull request by Rajesh-design158**
Hello sir or mamm tooday I interestin help OPEN SOURCE (im new to github and codeing).

i notice rendering and cunpiling times very high. I am pronpose changes inproving rendering timeings by up to 99%%!!!!! SEe plus plus has specmial thingie to append to line to mek it go brrr when cunpile and maybily ganple. (you pronbably know this mr see plus plus legend mr owouwuo) but codens bencome much faste!! 😄 

PS:
  ples unlock my issue 😢 i has to use virtual machine :((((

Thanks,
Rajesh Design LLC.

### CODE REVIEW

**Comment by ouwou** [comment]
Hm sir i Believe if u Inprove it a litle moar i may Consider Mernging

**Comment by Rajesh-design158** [comment]
🤯 thankks for responding kind sir,, what should I inprove on??? (first time making a pr 😄 😄 ) not cunpile fast enuf??? thank u once aagian kind sir 🙏 i hope to be in contact soonly 👍 

Thnaks,
Rajesh Design LLC.

**Comment by Rajesh-design158** [comment]
also, pls linux 😢 

i knooow maybe hard on linux??1! 🙄 but - --- if u do the needfuls 😄 😄 then easy?? 🥴 

Thanks,
Rajesh Design LLC.

**Comment by ouwou** [comment]
Yes sir if Conpile tiem is >1 second then i am Afrade i Cannot Axcept

**Comment by Rajesh-design158** [comment]
💯 💯 💯 🤯 fast response kind sir thank!!! I will be up all night kind sir ur kindness to a beginner lik e me is makingg me very happy (first time making pr 🧻 ) 😄 

I not sure if such time possible but i try 👍 👍 

have a GREAT DAY kind sir 😄 😸 

Thanks,
Rajesh Design LLC.

**Comment by ouwou** [comment]
Yes

**Comment by Rajesh-design158** [comment]
👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 👍 😄

**Pull request closed without merging**
