### PR TITLE
Big-endian 'emojis.bin' decoding fix

### PR DESCRIPTION
**Pull request by dragontamer8740**
See https://github.com/uowuo/abaddon/pull/97
Now synced up with `master` branch instead of `attachments`.

It finished compiling at last, and it ***does*** work fine on my PowerPC G4 (7447a) and amd64 (nehalem) machines both.

re: long compile times (from the other PR): yeah, it does take a while... but the powerbook is also just a dog performance-wise. It's much more bearable on my other hardware, especially because my other hardware has multiple execution cores.

### CODE REVIEW

**Comment by ouwou** [comment]
looks good just clang-format it (and if it turns `auto {` to `auto{` in line 93 just delete the `-> auto` i guess)

**Comment by dragontamer8740** [comment]
What? And why?

Never used clang-format before, don't even have it installed, and I'm not sure what it's supposed to do or where I am supposed to run it.

I'm installing it, but I really don't know why I'm doing this or what the point is.

**Comment by ouwou** [comment]
its for formatting but if you dont want to deal with it i think i can add it to the pr myself? ive never done that before though

**Comment by dragontamer8740** [comment]
See the update.
> BTW, when I run it like clang-format < chatinput.cpp > new.cpp and then diff chatinput.cpp and new.cpp I get no differences.

**Comment by dragontamer8740** [comment]
Brain fart.

emojis.cpp. not chatinput.cpp.

OK, coming up.

**Comment by ouwou** [comment]
the line 93 thing is because some versions of clang-format will screw up the trailing return type by removing the space even though it should be there

**Comment by dragontamer8740** [comment]
So why wasn't this done already? Why is that change being introduced by my PR?

And you want me to change

        auto get_text = [&]() -> auto {

to

        auto get_text = [&]() {

Correct?

**Comment by ouwou** [comment]
if clang-format doesnt do anything to the line then you can leave it be, and if it does modify it then you can just manually fix it so it remains unmodified. i just preemptively brought it up because clang-format might have incorrectly changed it.

**Comment by dragontamer8740** [comment]
Which it did. Ok, so I will add the space back in.

**Comment by dragontamer8740** [comment]
Done.

**Pull request merged**
