### PR TITLE
feat: `show_deleted_indicator`

### PR DESCRIPTION
**Pull request by TiranexDev**

### CODE REVIEW

**Comment by TiranexDev** [comment]
just found a issue, if I send one message and delete it, the user box is still shown. maybe any advice on how I can fix it?
image

**Comment by ouwou** [comment]
`RemoveMessageAndHeader(x);` should do what you want

**Comment by TiranexDev** [comment]
when using RemoveMessageAndHeader or ActuallyRemoveMessage this happens:

After sending 2 messages, deleting both (successfully) and trying to send a new message, the app crashes with a Segmentation fault, tried to debug it with gdb a bit

image

**Comment by ouwou** [comment]
im not entirely surprised RemoveMessageAndHeader breaks considering i only use it to cull messages from the top down, but a crash in `dynamic_cast` is weird... ill have a look myself in a bit

**Comment by TiranexDev** [comment]
> but a crash in `dynamic_cast` is weird...

Maybe it's just lack of my gdb skills, but thanks that you're going to look into that!

Whenever you'll fix it, let me know.

**Comment by ouwou** [comment]
okay, so you just need to do `m_id_to_widget.erase(id);` after `RemoveMessageAndHeader(x);`
poor design on my part, hopefully one day i get around to refactoring all the message shit :s

**Comment by ouwou** [comment]
also for README you just forgot a |

**Pull request merged**
