### PR TITLE
Attachments

### PR DESCRIPTION
**Pull request by ouwou**
- [x] paste images
- [ ] ~~paste files~~ (doesnt work on windows, api is stupid and annoying. might do another time)
- [x] drag and drop files
- [x] show preview for drag and dropped images (maybe not)
- [x] set filename
- [ ] ~~set caption~~ (maybe after captions are displayed)
- [ ] ~~mark as spoiler~~ (maybe after spoilers are displayed)
- [x] respect upload size restrictions
- [x] show filename and size inline when adding
- [ ] ~~do google cloud upload now because i guess the official client does that~~ later, when 500mb is rolled out
- [x] file picker
- [ ] make it look good

### CODE REVIEW

**Comment by ouwou** [comment]
i think that should do it for the file picker. maybe @dragontamer8740 has some input ?

**Comment by dragontamer8740** [comment]
Thanks; I will check it out sometime tomorrow or the next day.

**Comment by dragontamer8740** [comment]
Seems to work alright here.

**Comment by ouwou** [comment]
alright nice maybe i can finally call this finished lol

**Pull request merged**
