### PR TITLE
add clarity to linux install intruction

### PR DESCRIPTION
**Pull request by tawnylure**
I love clairty!

### CODE REVIEW

**Comment by tawnylure** [comment]
I hope this can be merged into the main branch.

**Comment by ouwou** [comment]
im not a big fan of the wording ("Download and drag"). theres already a section on resources too under the build instructions too ([link](https://github.com/uowuo/abaddon#resources)). it does seem to be easy to miss tho maybe something like this would be better:

6. [Copy resources](#resources)

this also isnt a linux-specific instruction so it should be added to win and macos too

**Comment by tawnylure** [comment]
> im not a big fan of the wording ("Download and drag"). theres already a section on resources too under the build instructions too ([link](https://github.com/uowuo/abaddon#resources)). it does seem to be easy to miss tho maybe something like this would be better:
> 
>     6. [Copy resources](#resources)
> 
> 
> this also isnt a linux-specific instruction so it should be added to win and macos too

Yeah, copy resources sounsd better.

**Comment by tawnylure** [comment]
Ok done, reworded it and added macos, hopefully we're good to push to main branch.

**Comment by ouwou** [comment]
changed it to a link to resources so its a little more general

**Pull request merged**
