### PR TITLE
add support for mac os platform detection to better understand error on startup

### PR DESCRIPTION
**Pull request by 9xN**

### CODE REVIEW

**Comment by 9xN** [comment]
added handling for "SESSIONS_REPLACE" (prints out that event occurred for now) pretty much just a template for actually handling it how you want to later on

**Comment by ouwou** [comment]
> added handling for "SESSIONS_REPLACE" (prints out that event occurred for now) pretty much just a template for actually handling it how you want to later on

id revert that cuz its unnecessary. i dont know if it even needs handling since it seems like a redundant event, besides its out of scope for the PR. also the change in audit log is wrong since its not something that exists in the audit log

anyways it looks ok and ill try and have someone who actually has a mac test it out themselves, but is `__MACH__` the proper macro? i doubt it will be an issue but i would double check to make sure its not like a compiler-specific thing

**Comment by ouwou** [comment]
also i know mac uses different paths. is there any reference for what applications generally use for things like config/state/resources?

**Comment by 9xN** [comment]
> also i know mac uses different paths. is there any reference for what applications generally use for things like config/state/resources?

nope except i personally would store them in a config folder in the same path as the executable and have a bash/zsh script to start the bloody thing from that path so it doesnt get screwed up other than that for rn i just put a folder with everything in the apple application folder and did that with bash aliases

**Comment by 9xN** [comment]
> also i know mac uses different paths. is there any reference for what applications generally use for things like config/state/resources?

the paths are the same not sure if i worded my last comment that well but yea things save to the dotfiles like they should

**Comment by 9xN** [comment]
Screen Shot 2022-05-29 at 1 05 20 AM

also this happened last night after a connection code error popped up...

**Comment by ouwou** [comment]
[this](https://developer.apple.com/library/archive/documentation/General/Conceptual/MOSXAppProgrammingGuide/AppRuntime/AppRuntime.html) seems to suggest that the current paths arent really the right location for mac. i dont even know if these directories can be written to since theres no notarization/code-signing or whatever goes on with mac's sandboxing. maybe you can give it a shot since if theres gonna be explicit handling for mac it probably shouldnt just be a copy of what linux does

**Comment by 9xN** [comment]
> [this](https://developer.apple.com/library/archive/documentation/General/Conceptual/MOSXAppProgrammingGuide/AppRuntime/AppRuntime.html) seems to suggest that the current paths arent really the right location for mac. i dont even know if these directories can be written to since theres no notarization/code-signing or whatever goes on with mac's sandboxing. maybe you can give it a shot since if theres gonna be explicit handling for mac it probably shouldnt just be a copy of what linux does
> 
> > also this happened last night after a connection code error popped up...
> 
> verification is basically an inevitability when not using the official client

considering that it literally works on mac with those exact paths to me at least would imply that it might still work on macos

**Comment by ouwou** [comment]
> considering that it literally works on mac with those exact paths to me at least would imply that it might still work on macos

well i was referring to the proper suggested paths not the xdg-type paths

**Comment by 9xN** [comment]
> > considering that it literally works on mac with those exact paths to me at least would imply that it might still work on macos
> 
> well i was referring to the proper suggested paths not the xdg-type paths

idk most well know and super popular applications for macos that are open source use those paths, personally i dont like it because they are harder to find but its not uncommon for other apps to use them

**Comment by ouwou** [comment]
> idk most well know and super popular applications for macos that are open source use those paths, personally i dont like it because they are harder to find but its not uncommon for other apps to use them

if you have specific examples then im curious in checking out what they do (if by "those paths" you mean ~/.local/share, ~/.config etc)

anyways if this is just a copy paste of the linux thing i would just modify the preprocessor directive from `#if defined(__linux__)` to `#if defined(__linux__) || defined(__MACH__)`

also like i said the SESSIONS_REPLACE stuff should go

**Comment by 9xN** [comment]
>if you have specific examples then im curious in checking out what they do (if by "those paths" you mean ~/.local/share, ~/.config etc)
yea

>anyways if this is just a copy paste of the linux thing i would just modify the preprocessor directive from #if defined(__linux__) to #if defined(__linux__) || defined(__MACH__)

left it open in case you wanted to use then change anything on it for more mac specific stuff or if you wanted me to actually spend some time and try to do this myself

>also like i said the SESSIONS_REPLACE stuff should go 

another "template" sort of thing and i can remove it but just out of curiosity do you have any future plans as to how to handle it instead? or as to why it shouldnt even log the event instead of letting it get caught as an error/invalid method?


also apologies for all my comments if they dont make sense at parts im not that strong in english yet its my third language so i hope that my point is still coming across :-)

**Comment by ouwou** [comment]
> yea

i mean can you give me some examples of mac software that writes to ~/.config and ~/.local/share? im sure they exist i just want to see what specifically they are doing

> left it open in case you wanted to use then change anything on it for more mac specific stuff or if you wanted me to actually spend some time and try to do this myself

if its just an exact duplicate i dont think theres a reason to keep them separate. if there comes a need to make mac do something special _then_ it can be split up

> another "template" sort of thing and i can remove it but just out of curiosity do you have any future plans as to how to handle it instead? or as to why it shouldnt even log the event instead of letting it get caught as an error/invalid method?

apart from it just being secondary to what the PR is about, theres no reason to try and handle it just to make the (one) console message go away. i guess the console spam is annoying or unnecessary but it shouldnt be handled unless its really "handled." as far as i know it doesnt actually need any handling, just like how VOICE_STATE_UPDATE is.

**Comment by dragontamer8740** [comment]
FWIW, and I have not used Mac OS for a while (snow leopard/10.6), `~/Library` is usually where programs save their settings.

**Comment by dragontamer8740** [comment]
Okay, here's an example of some different programs' layouts. mcomix and gimp primarily.

    user@users-iMac:~ $ find .config
    .config
    .config/gtk-3.0
    .config/mcomix
    .config/mcomix/preferences.conf
    .config/mcomix/keybindings.conf
    
    user@users-iMac:~ $ find .local
    .local
    .local/share
    .local/share/mcomix
    .local/share/mcomix/bookmarks.pickle
    .local/share/mcomix/library.db
    .local/share/mcomix/file.pickle
    .local/share/recently-used.xbel
    
    user@users-iMac:~ $ find Library | grep -i gimp
    Library/Application Support/GIMP
    Library/Application Support/GIMP/2.10
    Library/Application Support/GIMP/2.10/filters
    Library/Application Support/GIMP/2.10/plug-ins
    Library/Application Support/GIMP/2.10/brushes
    Library/Application Support/GIMP/2.10/interpreters
    Library/Application Support/GIMP/2.10/dockrc
    Library/Application Support/GIMP/2.10/dynamics
    Library/Application Support/GIMP/2.10/templaterc
    Library/Application Support/GIMP/2.10/patterns
    Library/Application Support/GIMP/2.10/sessionrc
    Library/Application Support/GIMP/2.10/controllerrc
    Library/Application Support/GIMP/2.10/gflare
    Library/Application Support/GIMP/2.10/toolrc
    Library/Application Support/GIMP/2.10/menurc
    Library/Application Support/GIMP/2.10/tool-options
    Library/Application Support/GIMP/2.10/tool-options/gimp-eraser-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-measure-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-by-color-select-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-paintbrush-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-handle-transform-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-fuzzy-select-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-curves-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-move-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-rect-select-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-gegl-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-foreground-select-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-unified-transform-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-mypaint-brush-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-rotate-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-cage-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-crop-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-bucket-fill-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-align-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-clone-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-warp-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-iscissors-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-shear-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-smudge-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-airbrush-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-dodge-burn-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-levels-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-convolve-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-free-select-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-perspective-clone-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-zoom-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-heal-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-flip-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-vector-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-color-picker-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-threshold-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-pencil-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-brightness-contrast-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-scale-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-ink-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-ellipse-select-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-operation-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-text-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-perspective-tool
    Library/Application Support/GIMP/2.10/tool-options/gimp-gradient-tool
    Library/Application Support/GIMP/2.10/gimpressionist
    Library/Application Support/GIMP/2.10/contextrc
    Library/Application Support/GIMP/2.10/internal-data
    Library/Application Support/GIMP/2.10/internal-data/custom.ggr
    Library/Application Support/GIMP/2.10/environ
    Library/Application Support/GIMP/2.10/parasiterc
    Library/Application Support/GIMP/2.10/tool-presets
    Library/Application Support/GIMP/2.10/icons
    Library/Application Support/GIMP/2.10/fractalexplorer
    Library/Application Support/GIMP/2.10/scripts
    Library/Application Support/GIMP/2.10/tags.xml
    Library/Application Support/GIMP/2.10/colorrc
    Library/Application Support/GIMP/2.10/unitrc
    Library/Application Support/GIMP/2.10/templates
    Library/Application Support/GIMP/2.10/themerc
    Library/Application Support/GIMP/2.10/gfig
    Library/Application Support/GIMP/2.10/levels
    Library/Application Support/GIMP/2.10/gradients
    Library/Application Support/GIMP/2.10/modules
    Library/Application Support/GIMP/2.10/fonts
    Library/Application Support/GIMP/2.10/tmp
    Library/Application Support/GIMP/2.10/gtkrc
    Library/Application Support/GIMP/2.10/action-history
    Library/Application Support/GIMP/2.10/themes
    Library/Application Support/GIMP/2.10/backups
    Library/Application Support/GIMP/2.10/palettes
    Library/Application Support/GIMP/2.10/profilerc
    Library/Application Support/GIMP/2.10/curves
    Library/Application Support/GIMP/2.10/gimprc
    Library/Application Support/GIMP/2.10/pluginrc
    Library/Application Support/GIMP/2.10/CrashLog
    Library/Application Support/GIMP/2.10/devicerc
    Library/Saved Application State/org.gimp.gimp-2.10:.savedState
    Library/Saved Application State/org.gimp.gimp-2.10:.savedState/window_1.data
    Library/Saved Application State/org.gimp.gimp-2.10:.savedState/windows.plist
    Library/Saved Application State/org.gimp.gimp-2.10:.savedState/data.data
    Library/Preferences/org.gimp.gimp-2.10:.plist

**Comment by ouwou** [comment]
closing for now since inactive but if the topic comes up again i can have another look

**Pull request closed without merging**
