### PR TITLE
Use a json file instead of an ini one to store settings

### PR DESCRIPTION
**Pull request by DyXel**
removes SimpleIni as dependency, plus we get all the other benefits of json.

This PR also includes a change to remove static usage in the linux part of platform.cpp

### CODE REVIEW

**Comment by NexAdn** [comment]
You might want to add that you've added nlohmann::json as a dependency. So basically you've exchanged one dependency with another.

First of all, why change?
Changing a config file format isn't something that should just be done.
There should at least be a migration mechanism since otherwise this _will_ break abaddon on _all_ systems.

Apart from that: Please elaborate on why ini isn't suitable as a config file format and what “benefits” json has over ini.

Other than that: I'm always in favor of removing submodules :sweat_smile: 

Of course, this is just my opinion. I'm not a maintainer.

**Comment by DyXel** [comment]
`nlohmann::json` was already being used through the whole codebase -- It's how discord interfaces transmit data.

There is no out of the shelf benefit right now; There aren't that many settings yet. But as the software develops, better ways to represent the data are going to be necessary, and I think its best to change right now rather than later. The core reason of this PR remains to remove an unnecessary dependency though.

**Comment by NexAdn** [comment]
> nlohmann::json was already being used through the whole codebase -- It's how discord interfaces transmit data.
Oh well, i certainly missed that one

> But as the software develops, better ways to represent the data are going to be necessary, and I think its best to change right now rather than later.
Well, do you have any scenarios in mind where a complex configuration structure is necessary? After all, it is a _configuration file_. This is the kind of file you would usually try to keep rather simple, since it is _intended_ to be edited by humans. Afaik JSON doesn't even support comments, so it's not really suited as a configuration file format (I have already worked with JSON-like configuration files for the Kea DHCP server).

ini is already a simple configuration file format which should be sufficient for all scenarios currently imaginable (after all, there isn't much apart from some key-value stuff configurable).

> The core reason of this PR remains to remove an unnecessary dependency though.
I'm definitely in favor of that one. Getting rid of unnecessary dependencies is always a good thing. And keeping the submodules up to date isn't really fun either.

Maybe you find a middle ground. Boost.program_options is very powerful and supports ini-like configuration files and Boost is already in the dependency tree (although just transitively: `abaddon -> gtkmm -> cairomm -> boost`).
Also, Boost has a property tree, which is a bit like JSON, but still supports comments depending in the [parser](https://www.boost.org/doc/libs/1_77_0/doc/html/property_tree/parsers.html), thus making it more useful as a configuration file format.

**Comment by ouwou** [comment]
>and Boost is already in the dependency tree

it seems cairomm only uses boost for tests so thats not really much of an option

>this will break abaddon on all systems

well wouldnt the impact here pretty much just be having to set your token again? simpleini is only a single header (wide character support is [disabled](https://github.com/uowuo/abaddon/blob/9d21df8e1bca9ccfa1bcfcde3bc8f35473866166/CMakeLists.txt#L25)). if the motivation is just to have less submodules perhaps it could be pulled in the same way murmurhash3 is (plus its barely updated), and since its only a single header wouldnt that alleviate (most of) the concerns of vendoring?

**Comment by NexAdn** [comment]
> well wouldnt the impact here pretty much just be having to set your token again?

In that case, writing a migration should be very easy. But again, think if you really want JSON as a configuration file format. Especially if they are in a minified form, JSON files can be hard to read and are thus not suited as a configuration file format. Of course, you might as well say that the file is not supposed to be edited manually. In that case, JSON is a sensible choice, although I hope not to see too much `#include <nlohmann/json.hpp>` in header files, since it increases the compile time by a few seconds for _every_ compile unit where it's included. abaddon already takes a very long time to compile for the few files it has ^^

> perhaps it could be pulled in the same way murmurhash3 is

Please, don't. When using submodules, one can at least _see_ that there is a vendored dependency. Copying it into the source tree still makes it a vendored dependency and – even worse – hides exactly that fact.

> and since its only a single header wouldnt that alleviate (most of) the concerns of vendoring?

Well, maybe. But the biggest problem from a distro maintainer's point of view with vendored dependencies is still, that the software maintainer is responsible for pulling in security updates. Of course, in this matter it isn't really a problem, but looking at IXWebsocket, it is very problematic, since the distro maintainer can't just update IXWebsocket to pull in security updates, but has to wait for the software maintainer to bring out a new release. See [Why not bundle dependencies (Gentoo Wiki)](https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies).

Currently, it's very easy to remove SimpleIni as a vendored dependency (I just have to patch a few lines in the CMakeLists.txt to force the correct include path and library name). Inserting it as a “hidden” vendored dependency makes this very hard even to notice.

**Comment by ouwou** [comment]
ok i wont do that then. but i thought i took care of the ixwebsocket+simpleini issue, they should be detected if present otherwise the submodules would be used as a fallback. if theres still something wrong there feel free to open another issue.

i agree with json being a little more annoying to deal with. maybe switching can wait until i add a proper settings window then you shouldnt have to touch the file at all (and if you do anyways after that then chances are you know what json is). ill have to sleep on it

**Comment by NexAdn** [comment]
> ok i wont do that then. but i thought i took care of the ixwebsocket+simpleini issue, they should be detected if present otherwise the submodules would be used as a fallback. if theres still something wrong there feel free to open another issue.
Since you've mentioned it, I checked again more thoroughly. ixwebsocket works like a charm (I also didn't have to patch CMakeLists.txt to make that one work). For SimpleIni, the problem probably needs to be solved by writing a find module since there is no unified installation method for simpleini (or rather, no hint on whether to put it in `/usr/include` or `/usr/include/simpleini`), but that doesn't really need to be solved if SimpleIni gets removed as a dependency. I could write a find module and submit a PR.

> i agree with json being a little more annoying to deal with. maybe switching can wait until i add a proper settings window then you shouldnt have to touch the file at all (and if you do anyways after that then chances are you know what json is).

That's fine, I guess. But still, it's your decision, not mine. I just have an opinion^^ I don't have a problem with migrating a single token to a new file format; I mainly wanted you to be sure you understand the consequences of a migration to the new format.

**Comment by ouwou** [comment]
i remembered that glib provides a parser for a format thats basically the same as ini and in my testing works basically the same. i feel pretty silly for not realizing that sooner but it is what it is. since the motivation here is removing the simpleini dependency ill close this in favor of using glib's keyfile stuff so the conversion of format doesnt have to be a concern.

**Pull request closed without merging**
