### PR TITLE
Fix for text wrapping in chat input - attachment branch edition

### PR DESCRIPTION
**Pull request by dragontamer8740**
Attachment branch had the same text wrapping problem previously fixed in main branch with https://github.com/uowuo/abaddon/pull/89.

Might want to just merge the other PR, but I figured I'd open a PR here, too.

(side note: I did not figure out how to "browse" for a file. Do I ***have*** to use an external file manager and drag, then? I usually don't have a graphical file manager at all.)

### CODE REVIEW

**Comment by ouwou** [comment]
the other one is already merged in master so theres no need to apply the same change. theres only drag and drop right now because it was easier to get up and running but ill make sure to add a file picker. file pickers might be a bit annoying because gtk on linux forces you to use their garbage file picker unless you enable some debug flag or install it in flatpak. i dont really understand the flatpak/portal stuff (i dont use linux much) but ill try to make it work well enough

**Comment by dragontamer8740** [comment]
@ouwou the way I have been dealing with that is using mcomix with an 'open file with' binding on a keyboard key that actually puts the full path to the file on the clipboard. Then I ctrl+l and paste, sidestepping the horrid gtk3 picker.

Also I use a patched libgtk that uses type-ahead find.

**Comment by ouwou** [comment]
>@ouwou the way I have been dealing with that is using mcomix with an 'open file with' binding on a keyboard key that actually puts the full path to the file on the clipboard. Then I ctrl+l and paste, sidestepping the horrid gtk3 picker.

well that doesnt work in this case right? or is this an image-only thing?

and its not exactly difficult to make a file picker pop up, but you have to worry about not blocking the gui thread and theres lots of other weird platform-specific stuff to prevent gtk from completely breaking when something creates it own window and has to handle input etc. either way gtk's [FileChooserNative](https://docs.gtk.org/gtk3/class.FileChooserNative.html#portal-details-gtkfilechooserdialognative-portal) should handle it?

maybe you can try to see if you can get it to popup with the correct file picker since you can already make one show up under server settings and clicking the server icon for a server which u have permission to edit the icon in. the workaround is to set GTK_USE_PORTAL=1 and have xdg-desktop-portal. would that be something that even works on fvwm?

**Comment by dragontamer8740** [comment]
@ouwou yes, I actually use portals to make the filechooser behave more acceptably in Firefox. Window managers have nothing to do with it, really, unless it's something like GNOME with all its dbus stuff going on.

Fair point about the threading; most of my applications don't have asynchronicity like a chat client would.

**Comment by ouwou** [comment]
alright well so long as you can get the file picker you want working from the server icon picker then i can make it work with the attachments upload too

**Comment by dragontamer8740** [comment]
Thank you so much.

Also thank you for your work on the program (and reverse engineering/documentation efforts). It makes my Powerbook G4 usable with discord when I have to use it instead of IRC for something.
Although I do have to add the `-latomic` linker flag on the final linking phase on that. And cmake doesn't seem to listen to CMAKE_EXE_LINKER_FLAGS when making it for some reason.

**Comment by ouwou** [comment]
i added a file picker in 344f2694141aa0cc8fc214dfd8ce2011df1a8079 in the attachments branch. theres still some things that need fixing up (hiding icon if u dont have permissions, restoring focus, etc). if u wanna lemme know what u think its probably better to leave it in #82

**Comment by dragontamer8740** [comment]
Thank you ^_^

I will check it out.

**Pull request closed without merging**
